### ISSUE TITLE
Logger module

### ISSUE THREAD

**Issue by Zaseth** [WorekServer/server#1]
Why not use Python's build in module for logging?

```python
import logging

logging.debug("Hello")
```

There's some more cool examples here: https://realpython.com/python-logging/

**Comment by ethanlindley** [comment]
I'll refactor the repo to use this. Thanks.

**Comment by ethanlindley** [comment]
Fixed in commit 25ffa1b3a9e8b5dcaa44918d6c2c086fd3adb43b
